
#HADOOP VARIABLES
export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64

export HADOOP_PREFIX=/home/hduser/hadoop
export HADOOP_HOME=$HADOOP_PREFIX
export HADOOP_COMMON_HOME=$HADOOP_PREFIX
export HADOOP_CONF_DIR=$HADOOP_PREFIX/etc/hadoop
export HADOOP_HDFS_HOME=$HADOOP_PREFIX
export HADOOP_MAPRED_HOME=$HADOOP_PREFIX
export HADOOP_YARN_HOME=$HADOOP_PREFIX
export YARN_CONF_DIR=$HADOOP_HOME/etc/hadoop

export HADOOP_DATA_DIR=$HADOOP_PREFIX/data/hdfs
export NN_DATA_DIR=$HADOOP_DATA_DIR/nn
export SNN_DATA_DIR=$HADOOP_DATA_DIR/snn
export DN_DATA_DIR=$HADOOP_DATA_DIR/dn

export HADOOP_LOG_DIR=$HADOOP_PREFIX/log/hadoop
export YARN_LOG_DIR=$HADOOP_LOG_DIR/yarn
export HADOOP_LOG_DIR=$HADOOP_LOG_DIR/hdfs
export HADOOP_MAPRED_LOG_DIR=$HADOOP_LOG_DIR/mapred

export HADOOP_RUN_DIR=$HADOOP_PREFIX/run/hadoop
export YARN_PID_DIR=$HADOOP_RUN_DIR/yarn
export HADOOP_PID_DIR=$HADOOP_RUN_DIR/hdfs
export HADOOP_MAPRED_PID_DIR=$HADOOP_RUN_DIR/mapred

export HADOOP_COMMON_LIB_NATIVE_DIR=$HADOOP_INSTALL/lib/native
export HADOOP_OPTS="-Djava.library.path=$HADOOP_INSTALL/lib"

export PATH=$PATH:$HADOOP_PREFIX/bin
export PATH=$PATH:$HADOOP_PREFIX/sbin
#HADOOP VARIABLES END
