#!/bin/bash

# sudo adduser hduser
# USE PASSWORD HADOOP

#Update
sudo apt-get update

#Install Java
sudo apt-get install -y default-jdk

#Generate SSH Key
echo -ne '\n' | ssh-keygen -t rsa -P ''
cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys

#Install Hadoop : http://www.apache.org/dyn/closer.cgi/hadoop/common/
wget http://a.mbbsindia.com/hadoop/common/stable2/hadoop-2.7.2.tar.gz
tar -xf hadoop-2.7.2.tar.gz
sudo mv hadoop-2.7.2 ~/hadoop

#Adding Hadoop Environment Variables File
cp .bashrc >> ~/.bashrc
source ~/.bashrc

rm *.tar.gz

#Adding Configuration Files
#cp conf/* ~/hadoop/etc/hadoop/

# hdfs dfs -mkdir -p /user/hduser